CREATE TABLE wallets (
    id          VARCHAR(64) PRIMARY KEY,
    balance     BIGINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT wallets_balance_non_negative CHECK (balance >= 0)
);

CREATE TABLE transfers (
    id               VARCHAR(64) PRIMARY KEY,
    idempotency_key  VARCHAR(255) NOT NULL UNIQUE,
    from_wallet_id   VARCHAR(64) NOT NULL REFERENCES wallets(id),
    to_wallet_id     VARCHAR(64) NOT NULL REFERENCES wallets(id),
    amount           BIGINT NOT NULL,
    status           VARCHAR(32) NOT NULL,
    failure_reason   VARCHAR(512),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT transfers_amount_positive CHECK (amount > 0),
    CONSTRAINT transfers_status_valid CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED')),
    CONSTRAINT transfers_distinct_wallets CHECK (from_wallet_id <> to_wallet_id)
);

CREATE INDEX idx_transfers_from_wallet ON transfers(from_wallet_id);
CREATE INDEX idx_transfers_to_wallet ON transfers(to_wallet_id);

CREATE TABLE ledger_entries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id    VARCHAR(64) NOT NULL REFERENCES wallets(id),
    transfer_id  VARCHAR(64) NOT NULL REFERENCES transfers(id),
    type         VARCHAR(16) NOT NULL,
    amount       BIGINT NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT ledger_type_valid CHECK (type IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ledger_amount_positive CHECK (amount > 0),
    CONSTRAINT ledger_unique_side UNIQUE (transfer_id, type)
);

CREATE INDEX idx_ledger_wallet ON ledger_entries(wallet_id);

CREATE TABLE idempotency_records (
    idempotency_key  VARCHAR(255) PRIMARY KEY,
    request_hash     VARCHAR(128) NOT NULL,
    transfer_id      VARCHAR(64) REFERENCES transfers(id),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
